version: 3

vars:
  git_root:
    sh: git rev-parse --show-toplevel
  go_root:
    sh: go env GOPATH
  go_version:
    sh: grep '^go ' ./go.mod | awk '{print $2}'
  go_lint: v1.60.3

  tasks:
    default:
      desc: Default task.
      cmds:
        - echo "Please enter a task or use '-l' or '--list-all' to list all available tasks"
      silent: true

    go/mod/vendor:
      desc: Run 'go mod vendor'.
      dir: "{{ .git_root }}"
      cmds:
        - |
          if [ -d "{{ .git_root }}/vendor" ]; then
            cd {{ .git_root }} && go mod tidy
          else 
            cd {{ .git_root }} && go mod tidy && go mod vendor
          fi
      internal: true
      silent: true

    go/lint/install:
      desc: Install 'golangci-lint'
      dir: "{{ .git_root }}"
      cmds:
        - cmd: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b {{ .go_root }}/bin {{ .golint_version }}
        - "{{ .go_root }}/bin/golangci-lint version"
      sources:
        - "{{ .go_root }}/bin/golangci-lint"
      internal: true
      silent: true

    go/lint/run:
      desc: Run 'golangci-lint'
      deps:
        - go/lint/install
      cmds: 
        - "{{ .go_root }}/bin/golangci-lint run"

    

