package forge

import (
	"github.com/Mad-Pixels/applingo-api/pkg/validator"
)

// CheckMetaFromAI represents metadata about the dictionary check generated by the AI.
// It includes a score and a reason.
type CheckMetaFromAI struct {
	Score  int    `json:"score" validate:"min=0,max=100"`
	Reason string `json:"reason" validate:"required"`
}

// Validate validates the CheckMetaFromAI fields using the applingo-api validator.
func (c *CheckMetaFromAI) Validate() error {
	return validator.New().ValidateStruct(c)
}

// ResponseDictionaryCheck represents the complete response payload for a dictionary check request.
// It includes the generated metadata and the original request parameters.
type ResponseDictionaryCheck struct {
	// Meta holds the metadata generated by openAI.
	Meta CheckMetaFromAI `json:"meta"`
}
