name: Build

on:
  workflow_call:

jobs:
  prepare:
    name: 🛠️ Prepare Functions
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get_functions.outputs.functions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and use applingo-builder
        run: |
          docker buildx create --name applingo-builder --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Detect functions in /cmd
        id: get_functions
        run: |
          FUNCTIONS=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "functions=${FUNCTIONS}" >> $GITHUB_OUTPUT
          echo "✅ Detected functions: ${FUNCTIONS}"

  build-function:
    name: 🐳 Build Function - ${{ matrix.function }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: ${{ fromJson(needs.prepare.outputs.functions) }}
    uses: Mad-Pixels/github-workflows/.github/workflows/invoke-task.yml@main
    with:
      command: docker/builds/func FUNC=${{ matrix.function }}