name: Build 

on:
  workflow_call:

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get_functions.outputs.functions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Find functions to build
        id: get_functions
        run: |
          FUNCTIONS=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "functions=${FUNCTIONS}" >> $GITHUB_OUTPUT
          echo "Functions: ${FUNCTIONS}"

  build-function:
    needs: prepare
    strategy:
      matrix:
        function: ${{ fromJson(needs.prepare.outputs.functions) }}
    
    uses: Mad-Pixels/github-workflows/.github/workflows/invoke-task.yml@main
    with:
      command: docker/build/func FUNC=${{ matrix.function }}