name: Images

on:
  workflow_call:
    inputs:
      base_ref:
        description: "Base reference for comparison (e.g. 'main')"
        required: false
        type: string
        default: "main"
    secrets:
      # AWS creds
      aws_secret_key:
        required: true
      aws_access_key:
        required: true
      aws_region: 
        required: true
      aws_account: 
        required: true

permissions:
  actions: write
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.set_functions.outputs.functions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find changed files
        id: changed
        run: |
          # Определяем, в каком контексте мы запущены
          echo "GitHub context info:"
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          
          if [ -n "${{ github.base_ref }}" ]; then
            # Мы в контексте PR
            BASE_REF="${{ github.base_ref }}"
            echo "Running in PR context, comparing with $BASE_REF"
            git diff --name-only origin/$BASE_REF...HEAD > changed_files.txt
          else
            # Мы в контексте Push или другом
            BASE_REF="${{ inputs.base_ref }}"
            CURRENT_SHA="${{ github.sha }}"
            PREV_SHA=$(git rev-parse $CURRENT_SHA^)
            
            echo "Running in push context, using base_ref: $BASE_REF"
            
            if [ "${{ github.event_name }}" == "push" ]; then
              echo "Comparing with previous commit"
              git diff --name-only $PREV_SHA $CURRENT_SHA > changed_files.txt
            else
              echo "Comparing with $BASE_REF branch"
              git fetch origin $BASE_REF
              git diff --name-only origin/$BASE_REF HEAD > changed_files.txt
            fi
          fi
          
          echo "Changed files:"
          cat changed_files.txt

      - name: Find functions to build
        id: set_functions
        run: |
          ALL_FUNCTIONS=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort)
          CHANGED_FILES=$(cat changed_files.txt)
          SHOULD_BUILD_ALL=false

          for file in $CHANGED_FILES; do
            if [[ "$file" == "go.mod" || "$file" == "Dockerfile" || "$file" == pkg/* || "$file" == openapi-interface/* || "$file" == lingo-interface/* || "$file" == dynamodb-interface/* ]]; then
              SHOULD_BUILD_ALL=true
              break
            fi
          done

          if [[ "$SHOULD_BUILD_ALL" == "true" ]]; then
            echo "Detected global changes, will build all functions."
            echo "functions=$(echo $ALL_FUNCTIONS | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
            exit 0
          fi

          CHANGED_FUNCTIONS=()
          for func in $ALL_FUNCTIONS; do
            if echo "$CHANGED_FILES" | grep -q "^cmd/$func/"; then
              CHANGED_FUNCTIONS+=("$func")
            fi
          done

          if [[ ${#CHANGED_FUNCTIONS[@]} -eq 0 ]]; then
            echo "No functions changed, skipping build."
            echo "functions=[]" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "functions=$(printf '%s\n' "${CHANGED_FUNCTIONS[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.functions != '[]' }}
    runs-on: ubuntu-latest
    name: ${{ matrix.function }}
    strategy:
      matrix:
        function: ${{ fromJson(needs.prepare.outputs.functions) }}

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Task with vars
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile@main
        with:
          command: docker/build/func
          vars: FUNC:${{ matrix.function }},ARCH:arm64
      
      - name: Push to ECR
        uses: Mad-Pixels/github-workflows/.github/actions/ecr-push@main
        with:
          aws_access_key_id: ${{ secrets.aws_access_key }}
          aws_secret_access_key: ${{ secrets.aws_secret_key }}
          aws_region: ${{ secrets.aws_region }}
          aws_account_id: ${{ secrets.aws_account }}
          image: applingo-images:${{ matrix.function }}