name: Checks

on:
  workflow_call:

jobs:
  terraform:
    name: TfFmt
    uses: Mad-Pixels/github-workflows/.github/workflows/terraform-fmt.yml@main
    with:
      tf_dir: ./terraform
  
  golang:
    name: GoLint
    runs-on: ubuntu-latest
    steps:
      - name: Run GoLint
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile@main
        with:
          command: go/run/lint

  tests:
    name: GoTest
    runs-on: ubuntu-latest
    steps:
      - name: Run Go Tests
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile@main
        with:
          command: go/run/tests
  
  leaks:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ./gitleaks.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
