name: Images

on:
  workflow_call:

permissions:
  actions: write
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      functions: ${{ steps.get_functions.outputs.functions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Find functions to build
        id: get_functions
        run: |
          FUNCTIONS=$(find ./cmd -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "functions=${FUNCTIONS}" >> $GITHUB_OUTPUT
          echo "Functions: ${FUNCTIONS}"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: ${{ fromJson(needs.prepare.outputs.functions) }}

    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Task with vars
        uses: Mad-Pixels/github-workflows/.github/actions/taskfile@main
        with:
          command: docker/build/func
          vars: FUNC:${{ matrix.function }},ARCH:arm64
