name: Terraform 

on:
  workflow_call:
    inputs:
      environment:
        type: string
      tf_command:
        type: string
    secrets:
      # AWS creds
      aws_secret_key:
        required: true
      aws_access_key:
        required: true
      aws_region: 
        required: true

      # TF Backend
      aws_backend_bucket:
        required: true
      aws_backend_region:
        required: true

      # TF Backend keys
      aws_backend_infra_key:
        required: true
      aws_backend_monitoring_key:
        required: true
      aws_backend_service_key:
        required: true

      # TF vars
      api_web_jwt_stg:
        required: true
      api_openai_key_stg:
        required: true
      api_device_key_stg:
        required: true

jobs:
  tf-infra:
    name: Tf Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/terraform@main
        with:
          aws_access_key_id:     ${{ secrets.aws_access_key }}
          aws_secret_access_key: ${{ secrets.aws_secret_key }}
          aws_region:            ${{ secrets.aws_region }}

          backend_bucket:        ${{ secrets.aws_backend_bucket }}-${{ inputs.environment }}
          backend_key:           ${{ secrets.aws_backend_infra_key }}
          backend_region:        ${{ secrets.aws_backend_region }}

          tf_dir:                terraform/provisioners/infra
          tf_command:            ${{ inputs.tf_command }}
          tf_vars: >-
            -var environment=${{ inputs.environment }}

  tf-monitoring:
    name: Tf Monitoring
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/terraform@main
        with:
          aws_access_key_id:     ${{ secrets.aws_access_key }}
          aws_secret_access_key: ${{ secrets.aws_secret_key }}
          aws_region:            ${{ secrets.aws_region }}

          backend_bucket:        ${{ secrets.aws_backend_bucket }}-${{ inputs.environment }}
          backend_key:           ${{ secrets.aws_backend_monitoring_key }}
          backend_region:        ${{ secrets.aws_backend_region }}

          tf_dir:                terraform/provisioners/monitoring
          tf_command:            ${{ inputs.tf_command }}
          tf_vars: >-
            -var domain_name=""
            -var domain_zone_id=""
            -var domain_acm_arn=""

  tf-service:
    needs: tf-infra
    name: Tf Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Invoke
        uses: Mad-Pixels/github-workflows/.github/actions/terraform@main
        with:
          aws_access_key_id:     ${{ secrets.aws_access_key }}
          aws_secret_access_key: ${{ secrets.aws_secret_key }}
          aws_region:            ${{ secrets.aws_region }}

          backend_bucket:        ${{ secrets.aws_backend_bucket }}-${{ inputs.environment }}
          backend_key:           ${{ secrets.aws_backend_service_key }}
          backend_region:        ${{ secrets.aws_backend_region }}

          tf_dir:                terraform/provisioners/service
          tf_command:            ${{ inputs.tf_command }}
          tf_vars: >-
            -var infra_backend_bucket=${{ secrets.aws_backend_bucket }}-${{ inputs.environment }}
            -var infra_backend_region=${{ secrets.aws_backend_region }}
            -var infra_backend_key=${{ secrets.aws_backend_infra_key }}
            -var environment=${{ inputs.environment }}
            -var jwt_secret=${{ secrets.api_web_jwt_stg }}
            -var openai_key=${{ secrets.api_openai_key_stg }}
            -var device_api_token=${{ secrets.api_device_key_stg }}
            -var arch="arm64"