name: Base PR

on:
  pull_request:
    types: [opened, synchronize]
    branches-ignore:
      - main
      - release/**

concurrency:
  group: base-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  checks:
    name: (Base) Pr Checks
    uses: ./.github/workflows/.checks.yml