name: Linter

on:
  push:
    branches: ["**"]

jobs:
  terraform:
    uses: Mad-Pixels/github-workflows/.github/workflows/terraform-fmt.yml@main
    with:
      tf_dir: ./terraform
  
  golang:
    uses: Mad-Pixels/github-workflows/.github/workflows/invoke-task.yml@main
    with:
      command: "go/run/lint"


    
