name: Release Commit

on:
  push:
    branches:
      - release/**

concurrency:
  group: release-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-commit:
    name: Check if regular commit
    runs-on: ubuntu-latest
    outputs:
      proceed: ${{ steps.commit_check.outputs.proceed }}
    steps:
      - name: IsCommit 
        id: commit_check
        uses: Mad-Pixels/github-workflows/.github/actions/is-commit@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  checks:
    name: (STG) Commit Checks
    needs: [check-commit]
    if: needs.check-commit.outputs.proceed == 'true'
    uses: ./.github/workflows/.checks.yml
    secrets:
      gitleaks: ${{ secrets.GITLEAKS_LICENSE }}

  build:
    name: (STG) Build
    needs: [checks]
    if: needs.check-commit.outputs.proceed == 'true'
    uses: ./.github/workflows/.build.yml
    with:
      base_ref: ${{ github.ref_name }}
    secrets:
      aws_secret_key:             ${{ secrets.AWS_SECRET_KEY_STG }}
      aws_access_key:             ${{ secrets.AWS_ACCESS_KEY_STG }}
      aws_region:                 ${{ secrets.AWS_REGION }}
      aws_account:                ${{ secrets.AWS_ACCOUNT_ID_STG }}

  apply:
    name: (STG) Apply
    needs: [checks]
    if: needs.check-commit.outputs.proceed == 'true'
    uses: ./.github/workflows/.terraform.yml
    with:
      environment: "stg"
      tf_command: "apply"
    secrets:
      aws_secret_key:             ${{ secrets.AWS_SECRET_KEY_STG }}
      aws_access_key:             ${{ secrets.AWS_ACCESS_KEY_STG }}
      aws_region:                 ${{ secrets.AWS_REGION }}
      aws_monitoring_bucket:      ${{ secrets.AWS_MONITORING_BUCKET }}-stg
      aws_backend_bucket:         ${{ secrets.AWS_BACKEND_BUCKET }}
      aws_backend_region:         ${{ secrets.AWS_BACKEND_REGION }}
      aws_backend_monitoring_key: ${{ secrets.AWS_BACKEND_MONITORING_KEY }}
      aws_backend_service_key:    ${{ secrets.AWS_BACKEND_SERVICE_KEY }}
      aws_backend_infra_key:      ${{ secrets.AWS_BACKEND_INFRA_KEY }}
      api_web_jwt_stg:            ${{ secrets.API_WEB_JWT_STG }}
      api_openai_key_stg:         ${{ secrets.API_OPENAI_KEY_STG }}
      api_device_key_stg:         ${{ secrets.API_DEVICE_KEY_STG }}

  rollout:
    name: (STG) Rollout
    needs: [apply, build]
    if: needs.check-commit.outputs.proceed == 'true'
    uses: ./.github/workflows/.rollout.yml
    secrets:
      aws_secret_key:             ${{ secrets.AWS_SECRET_KEY_STG }}
      aws_access_key:             ${{ secrets.AWS_ACCESS_KEY_STG }}
      aws_region:                 ${{ secrets.AWS_REGION }}
      aws_account:                ${{ secrets.AWS_ACCOUNT_ID_STG }}