name: AWS Terraform Plan

on:
  push:
    branches: ["**"]

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

      TF_DIR: "./terraform/provisioners/monitoring"

      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_use_localstack: "false"
      TF_VAR_domain_name: ${{ secrets.AWS_MONITORING_DOMAIN }}
      TF_VAR_domain_zone_id: ${{ secrets.AWS_DOMAIN_ZONE_ID }}
      TF_VAR_domain_acm_arn: ${{ secrets.AWS_MONITORING_ACM }}
      
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_DIR }}
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.1
        
    - name: Create backend_aws.hcl
      run: |
        cat > backend_aws.hcl << 'EOF'
        bucket  = "${{ secrets.AWS_BACKEND_BUCKET }}"
        key     = "${{ secrets.AWS_BACKEND_MONITORING_KEY }}"
        region  = "${{ secrets.AWS_BACKEND_REGION }}"
        encrypt = true
        EOF

    - name: Create backend 
      run: |
        cat << EOF > backend.tf
        terraform {
          backend "s3" {}
        }
        EOF
      
    - name: Terraform Init
      run: terraform init -reconfigure -backend-config=backend_aws.hcl
      
    - name: Terraform Format Check
      run: terraform fmt -check
      
    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan
      run: terraform plan 
      id: plan
      
    - name: Output Plan
      run: echo "${{ steps.plan.outputs.stdout }}"